### ISSUE TITLE
KeyError: 0 when running __main__.py

### ISSUE THREAD

**Issue by MartinKondor** [MartinKondor/PersonalityAnalyzer#1]
When running `python .` in the main directory, I get this error:
```
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
Traceback (most recent call last):
  File "/Users/martinkondor/miniforge3/envs/tf24/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/martinkondor/miniforge3/envs/tf24/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 43, in <module>
    predictor = MBType()
  File "./__main__.py", line 13, in __init__
    self.vectorizer = load_prep('trained/vectorizer.pkl')
  File "/Users/martinkondor/miniforge3/envs/tf24/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/Users/martinkondor/miniforge3/envs/tf24/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/Users/martinkondor/miniforge3/envs/tf24/lib/python3.8/pickle.py", line 1210, in load
    dispatch[key[0]](self)
KeyError: 0
Loading the model...
```

**Comment by MartinKondor** [comment]
Possibly because the model was saved with a previous installation of `sklearn`. A new model release might resolve this issue.
